services:
  - type: web
    name: endee-rag-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: endee-rag-frontend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: BACKEND_HOSTPORT
        fromService:
          type: web
          name: endee-rag-backend
          envVarKey: hostport
